// Generated by gencpp from file my_srv/VelocityRequest.msg
// DO NOT EDIT!


#ifndef MY_SRV_MESSAGE_VELOCITYREQUEST_H
#define MY_SRV_MESSAGE_VELOCITYREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_srv
{
template <class ContainerAllocator>
struct VelocityRequest_
{
  typedef VelocityRequest_<ContainerAllocator> Type;

  VelocityRequest_()
    : x(0.0)  {
    }
  VelocityRequest_(const ContainerAllocator& _alloc)
    : x(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;





  typedef boost::shared_ptr< ::my_srv::VelocityRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_srv::VelocityRequest_<ContainerAllocator> const> ConstPtr;

}; // struct VelocityRequest_

typedef ::my_srv::VelocityRequest_<std::allocator<void> > VelocityRequest;

typedef boost::shared_ptr< ::my_srv::VelocityRequest > VelocityRequestPtr;
typedef boost::shared_ptr< ::my_srv::VelocityRequest const> VelocityRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_srv::VelocityRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_srv::VelocityRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace my_srv

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::my_srv::VelocityRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_srv::VelocityRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_srv::VelocityRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_srv::VelocityRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_srv::VelocityRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_srv::VelocityRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_srv::VelocityRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "abd5d1e9c3ac157a0df3ba27b65d3384";
  }

  static const char* value(const ::my_srv::VelocityRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xabd5d1e9c3ac157aULL;
  static const uint64_t static_value2 = 0x0df3ba27b65d3384ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_srv::VelocityRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_srv/VelocityRequest";
  }

  static const char* value(const ::my_srv::VelocityRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_srv::VelocityRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n\
";
  }

  static const char* value(const ::my_srv::VelocityRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_srv::VelocityRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VelocityRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_srv::VelocityRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_srv::VelocityRequest_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_SRV_MESSAGE_VELOCITYREQUEST_H
