// Generated by gencpp from file my_srv/Velocity.msg
// DO NOT EDIT!


#ifndef MY_SRV_MESSAGE_VELOCITY_H
#define MY_SRV_MESSAGE_VELOCITY_H

#include <ros/service_traits.h>


#include <my_srv/VelocityRequest.h>
#include <my_srv/VelocityResponse.h>


namespace my_srv
{

struct Velocity
{

typedef VelocityRequest Request;
typedef VelocityResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Velocity
} // namespace my_srv


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::my_srv::Velocity > {
  static const char* value()
  {
    return "40ea698aabf8704efca157e322fec61c";
  }

  static const char* value(const ::my_srv::Velocity&) { return value(); }
};

template<>
struct DataType< ::my_srv::Velocity > {
  static const char* value()
  {
    return "my_srv/Velocity";
  }

  static const char* value(const ::my_srv::Velocity&) { return value(); }
};


// service_traits::MD5Sum< ::my_srv::VelocityRequest> should match 
// service_traits::MD5Sum< ::my_srv::Velocity > 
template<>
struct MD5Sum< ::my_srv::VelocityRequest>
{
  static const char* value()
  {
    return MD5Sum< ::my_srv::Velocity >::value();
  }
  static const char* value(const ::my_srv::VelocityRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_srv::VelocityRequest> should match 
// service_traits::DataType< ::my_srv::Velocity > 
template<>
struct DataType< ::my_srv::VelocityRequest>
{
  static const char* value()
  {
    return DataType< ::my_srv::Velocity >::value();
  }
  static const char* value(const ::my_srv::VelocityRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::my_srv::VelocityResponse> should match 
// service_traits::MD5Sum< ::my_srv::Velocity > 
template<>
struct MD5Sum< ::my_srv::VelocityResponse>
{
  static const char* value()
  {
    return MD5Sum< ::my_srv::Velocity >::value();
  }
  static const char* value(const ::my_srv::VelocityResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_srv::VelocityResponse> should match 
// service_traits::DataType< ::my_srv::Velocity > 
template<>
struct DataType< ::my_srv::VelocityResponse>
{
  static const char* value()
  {
    return DataType< ::my_srv::Velocity >::value();
  }
  static const char* value(const ::my_srv::VelocityResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MY_SRV_MESSAGE_VELOCITY_H
