// Generated by gencpp from file my_srv2/RandomRequest.msg
// DO NOT EDIT!


#ifndef MY_SRV2_MESSAGE_RANDOMREQUEST_H
#define MY_SRV2_MESSAGE_RANDOMREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_srv2
{
template <class ContainerAllocator>
struct RandomRequest_
{
  typedef RandomRequest_<ContainerAllocator> Type;

  RandomRequest_()
    : min(0.0)
    , max(0.0)  {
    }
  RandomRequest_(const ContainerAllocator& _alloc)
    : min(0.0)
    , max(0.0)  {
  (void)_alloc;
    }



   typedef float _min_type;
  _min_type min;

   typedef float _max_type;
  _max_type max;





  typedef boost::shared_ptr< ::my_srv2::RandomRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_srv2::RandomRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RandomRequest_

typedef ::my_srv2::RandomRequest_<std::allocator<void> > RandomRequest;

typedef boost::shared_ptr< ::my_srv2::RandomRequest > RandomRequestPtr;
typedef boost::shared_ptr< ::my_srv2::RandomRequest const> RandomRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_srv2::RandomRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_srv2::RandomRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace my_srv2

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::my_srv2::RandomRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_srv2::RandomRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_srv2::RandomRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_srv2::RandomRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_srv2::RandomRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_srv2::RandomRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_srv2::RandomRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b3ee9ed25575b46bb47c7673ad202faa";
  }

  static const char* value(const ::my_srv2::RandomRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb3ee9ed25575b46bULL;
  static const uint64_t static_value2 = 0xb47c7673ad202faaULL;
};

template<class ContainerAllocator>
struct DataType< ::my_srv2::RandomRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_srv2/RandomRequest";
  }

  static const char* value(const ::my_srv2::RandomRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_srv2::RandomRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 min\n\
float32 max\n\
";
  }

  static const char* value(const ::my_srv2::RandomRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_srv2::RandomRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.min);
      stream.next(m.max);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RandomRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_srv2::RandomRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_srv2::RandomRequest_<ContainerAllocator>& v)
  {
    s << indent << "min: ";
    Printer<float>::stream(s, indent + "  ", v.min);
    s << indent << "max: ";
    Printer<float>::stream(s, indent + "  ", v.max);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_SRV2_MESSAGE_RANDOMREQUEST_H
