// Generated by gencpp from file my_srv2/Random.msg
// DO NOT EDIT!


#ifndef MY_SRV2_MESSAGE_RANDOM_H
#define MY_SRV2_MESSAGE_RANDOM_H

#include <ros/service_traits.h>


#include <my_srv2/RandomRequest.h>
#include <my_srv2/RandomResponse.h>


namespace my_srv2
{

struct Random
{

typedef RandomRequest Request;
typedef RandomResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Random
} // namespace my_srv2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::my_srv2::Random > {
  static const char* value()
  {
    return "a8aaa1c47035b235557a85c38913cbf8";
  }

  static const char* value(const ::my_srv2::Random&) { return value(); }
};

template<>
struct DataType< ::my_srv2::Random > {
  static const char* value()
  {
    return "my_srv2/Random";
  }

  static const char* value(const ::my_srv2::Random&) { return value(); }
};


// service_traits::MD5Sum< ::my_srv2::RandomRequest> should match 
// service_traits::MD5Sum< ::my_srv2::Random > 
template<>
struct MD5Sum< ::my_srv2::RandomRequest>
{
  static const char* value()
  {
    return MD5Sum< ::my_srv2::Random >::value();
  }
  static const char* value(const ::my_srv2::RandomRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_srv2::RandomRequest> should match 
// service_traits::DataType< ::my_srv2::Random > 
template<>
struct DataType< ::my_srv2::RandomRequest>
{
  static const char* value()
  {
    return DataType< ::my_srv2::Random >::value();
  }
  static const char* value(const ::my_srv2::RandomRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::my_srv2::RandomResponse> should match 
// service_traits::MD5Sum< ::my_srv2::Random > 
template<>
struct MD5Sum< ::my_srv2::RandomResponse>
{
  static const char* value()
  {
    return MD5Sum< ::my_srv2::Random >::value();
  }
  static const char* value(const ::my_srv2::RandomResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_srv2::RandomResponse> should match 
// service_traits::DataType< ::my_srv2::Random > 
template<>
struct DataType< ::my_srv2::RandomResponse>
{
  static const char* value()
  {
    return DataType< ::my_srv2::Random >::value();
  }
  static const char* value(const ::my_srv2::RandomResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MY_SRV2_MESSAGE_RANDOM_H
