// Generated by gencpp from file my_srv2/Velocity2Response.msg
// DO NOT EDIT!


#ifndef MY_SRV2_MESSAGE_VELOCITY2RESPONSE_H
#define MY_SRV2_MESSAGE_VELOCITY2RESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_srv2
{
template <class ContainerAllocator>
struct Velocity2Response_
{
  typedef Velocity2Response_<ContainerAllocator> Type;

  Velocity2Response_()
    : x(0.0)
    , y(0.0)  {
    }
  Velocity2Response_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;





  typedef boost::shared_ptr< ::my_srv2::Velocity2Response_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_srv2::Velocity2Response_<ContainerAllocator> const> ConstPtr;

}; // struct Velocity2Response_

typedef ::my_srv2::Velocity2Response_<std::allocator<void> > Velocity2Response;

typedef boost::shared_ptr< ::my_srv2::Velocity2Response > Velocity2ResponsePtr;
typedef boost::shared_ptr< ::my_srv2::Velocity2Response const> Velocity2ResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_srv2::Velocity2Response_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_srv2::Velocity2Response_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace my_srv2

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::my_srv2::Velocity2Response_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_srv2::Velocity2Response_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_srv2::Velocity2Response_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_srv2::Velocity2Response_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_srv2::Velocity2Response_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_srv2::Velocity2Response_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_srv2::Velocity2Response_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ff8d7d66dd3e4b731ef14a45d38888b6";
  }

  static const char* value(const ::my_srv2::Velocity2Response_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xff8d7d66dd3e4b73ULL;
  static const uint64_t static_value2 = 0x1ef14a45d38888b6ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_srv2::Velocity2Response_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_srv2/Velocity2Response";
  }

  static const char* value(const ::my_srv2::Velocity2Response_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_srv2::Velocity2Response_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n\
float32 y\n\
\n\
";
  }

  static const char* value(const ::my_srv2::Velocity2Response_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_srv2::Velocity2Response_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Velocity2Response_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_srv2::Velocity2Response_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_srv2::Velocity2Response_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_SRV2_MESSAGE_VELOCITY2RESPONSE_H
