// Generated by gencpp from file turtlebot_controller/Vel.msg
// DO NOT EDIT!


#ifndef TURTLEBOT_CONTROLLER_MESSAGE_VEL_H
#define TURTLEBOT_CONTROLLER_MESSAGE_VEL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace turtlebot_controller
{
template <class ContainerAllocator>
struct Vel_
{
  typedef Vel_<ContainerAllocator> Type;

  Vel_()
    : name()
    , vel(0.0)  {
    }
  Vel_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , vel(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef float _vel_type;
  _vel_type vel;





  typedef boost::shared_ptr< ::turtlebot_controller::Vel_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtlebot_controller::Vel_<ContainerAllocator> const> ConstPtr;

}; // struct Vel_

typedef ::turtlebot_controller::Vel_<std::allocator<void> > Vel;

typedef boost::shared_ptr< ::turtlebot_controller::Vel > VelPtr;
typedef boost::shared_ptr< ::turtlebot_controller::Vel const> VelConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtlebot_controller::Vel_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtlebot_controller::Vel_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace turtlebot_controller

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'turtlebot_controller': ['/root/my_ros2/my_ros_ws/src/turtlebot_controller/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::turtlebot_controller::Vel_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtlebot_controller::Vel_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtlebot_controller::Vel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtlebot_controller::Vel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlebot_controller::Vel_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlebot_controller::Vel_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtlebot_controller::Vel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0cf99747c25a22990a63da10629b2c8c";
  }

  static const char* value(const ::turtlebot_controller::Vel_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0cf99747c25a2299ULL;
  static const uint64_t static_value2 = 0x0a63da10629b2c8cULL;
};

template<class ContainerAllocator>
struct DataType< ::turtlebot_controller::Vel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtlebot_controller/Vel";
  }

  static const char* value(const ::turtlebot_controller::Vel_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtlebot_controller::Vel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n\
float32 vel\n\
";
  }

  static const char* value(const ::turtlebot_controller::Vel_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtlebot_controller::Vel_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.vel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Vel_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtlebot_controller::Vel_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtlebot_controller::Vel_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "vel: ";
    Printer<float>::stream(s, indent + "  ", v.vel);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLEBOT_CONTROLLER_MESSAGE_VEL_H
